name: chasis_admin
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ">=3.3.0 <4.0.0"

dependencies:
  app_core:
    path: packages/flutter_core_package
  dio: ^5.9.2
  flutter:
    sdk: flutter
  flutter_bloc: ^9.1.1
  get_it: ^9.2.1
  go_router: ^17.1.0
  hive_ce: ^2.19.3
  hive_ce_flutter: ^2.3.4
  path_provider: ^2.1.2
  encrypt: ^5.0.3
  flutter_secure_storage: ^9.2.2
  shadcn_ui: ^0.53.5

dev_dependencies:
  bloc_test: ^10.0.0
  build_runner: ^2.4.9
  hive_ce_generator: ^1.11.1
  flutter_lints: ^3.0.0
  flutter_test:
    sdk: flutter
  mocktail: ^1.0.4
  flutter_driver:
    sdk: flutter

flutter:
  uses-material-design: true

dependency_overrides:
  test_api: 0.7.7
